In [3]:
import pandas
import search.searchengine as se

df = pandas.DataFrame.from_dict(se.search('game'))
df

,id,name,slug,status,accepted_invites_count,subscription,aliases
0,807,Game,game,ACTIVE,1,{'name': 'Free'},"[{'id': 2415, 'org_id': 807, 'alias': 'Game St..."
1,987740,GameMine,gamemine,ACTIVE,2,{'name': 'G1'},"[{'id': 36005, 'org_id': 987740, 'alias': 'Gam..."
2,851931,Gameoflife,gameoflife,SUSPENDED,0,None,"[{'id': 3872, 'org_id': 851931, 'alias': 'Game..."
3,1117,BT Games,bt-games,SUSPENDED,0,None,"[{'id': 76, 'org_id': 1117, 'alias': 'Bt Game'..."
4,748956,Askari Lodge & Plumari Game Reserve,askari-lodge-plumari-game-reserve,SUSPENDED,0,None,"[{'id': 1293, 'org_id': 748956, 'alias': 'Plum..."
5,988229,Game 4U,game-4u,None,1,{'name': 'Free'},"[{'id': 31575, 'org_id': 988229, 'alias': 'Gam..."
6,759183,Tala Private Game Reserve,tala-private-game-reserve,SUSPENDED,0,None,"[{'id': 11726, 'org_id': 759183, 'alias': 'Tal..."
7,784671,African Explorer Private Game Lodge,african-explorer-private-game-lodge,SUSPENDED,0,None,"[{'id': 1084, 'org_id': 784671, 'alias': 'Afri..."
8,941597,Mbizi Game Lodge,mbizi-game-lodge,PENDING,0,None,"[{'id': 49494, 'org_id': 941597, 'alias': 'Mbi..."
9,924609,Cradle Moon Lakeside Game Lodge,cradle-moon-lakeside-game-lodge,PENDING,0,None,"[{'id': 43962, 'org_id': 924609, 'alias': 'Cra..."